services:
  postgres:
    image: postgres:16-alpine
    container_name: cineapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cineapi
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cineapi-network

volumes:
  postgres_data:

networks:
  cineapi-network:
    driver: bridge
